import { ApiProperty } from '@nestjs/swagger';
import { GrindType } from '../../../common/enums/grind-type.enum';

class TopProductDto {
  @ApiProperty({ description: 'ID of the product stock item' })
  id: string;

  @ApiProperty({ description: 'SKU of the product stock item' })
  sku: string;

  @ApiProperty({ description: 'Name of the product from catalog' })
  productName: string;

  @ApiProperty({ description: 'Grind type of the product', enum: GrindType })
  grindType: GrindType;

  @ApiProperty({ description: 'Total quantity sold for this product' })
  totalSold: number;

  @ApiProperty({ description: 'Total revenue generated by this product' })
  totalRevenue: number;
}

export class DashboardTopProductsDto {
  @ApiProperty({ type: [TopProductDto], description: 'List of top products by quantity sold' })
  topProducts: TopProductDto[];
}
