export enum ExpenseCategory {
  TRANSPORT = 'TRANSPORT',
  PACKAGING = 'PACKAGING',
  SUPPLIES = 'SUPPLIES',
  SERVICES = 'SERVICES',
  OTHER = 'OTHER',
  PURCHASE = 'PURCHASE',
  PRODUCTION = 'PRODUCTION',
}
