export enum InventoryMovementReason {
  BATCH_PURCHASE = 'BATCH_PURCHASE',
  MICROBATCH_PRODUCTION = 'MICROBATCH_PRODUCTION',
  SALE = 'SALE',
  ADJUSTMENT = 'ADJUSTMENT',
  RETURN = 'RETURN',
  OTHER = 'OTHER',
}
